### ISSUE TITLE
Invalid control type when using $PARAM

### ISSUE THREAD

**Issue by mistervee** [phil65/KodiDevKit#9]
i.e.

`<control type="$PARAM[listtype]" id="9000">`

**Comment by phil65** [comment]
hmm i think i already fixed this some time ago?
https://github.com/phil65/KodiDevKit/commit/9fd263c3b4259b58a1081364b59550baa9331d1e

**Comment by mistervee** [comment]
I have done some sanity checks. Removed and reinstalled kodi dev kit. v2.6.2, and checked the console for any error. 

Still getting the invalid control type.

I see this in the console, https://imgur.com/a/bf9e4
```
mdpopups: Failed to convert/retrieve scheme to CSS!
mdpopups: Failed to get Sublime highlighter object!
```

The xml
https://pastebin.com/P6eHSsSd

**Comment by phil65** [comment]
oh, sorry. I'm an idiot. :)
Should be fixed with https://github.com/phil65/KodiDevKit/commit/8388024ceb397217d0a0852e6dc68522628407ff

**Comment by mistervee** [comment]
Cheers Phil

Working Great. :+1:
